let presetAdventureTime = {
  avatar: "Adventure Time",
  bgFrameColor: "#ffd93f",
  bgFrameOpacity: 1,
  bgFramePosY: 160,
  bgOnlyPosYOffset: 0,
  dividedLineColor: "#202020",
  dividedLinePosY: 12,
  dividedLineStyle: "Wavy",
  line1Color: "#009bdf",
  line1PosY: 2,
  line1Size: 38,
  line1Spacing: 0,
  line1Text: "NEXT",
  line2Color: "#ed0080",
  line2PosY: 50,
  line2Size: 24,
  line2Spacing: 0,
  line2Text: "ADVENTURE TIME",
  updateAnim: false
};

let presetThisIsUs = {
  avatar: "This Is Us",
  bgFrameColor: "#ffd93f",
  bgFrameOpacity: 1,
  bgFramePosY: 160,
  bgOnlyPosYOffset: 0,
  dividedLineColor: "#202020",
  dividedLinePosY: 10,
  dividedLineStyle: "Wavy",
  line1Color: "#009bdf",
  line1PosY: 4,
  line1Size: 34,
  line1Spacing: 0,
  line1Text: "TONIGHT &nbsp;9/8c",
  line2Color: "#ed0080",
  line2PosY: 50,
  line2Size: 24,
  line2Spacing: 0,
  line2Text: "THIS IS US",
  updateAnim: false
};

let presetJimmyKimmelLive = {
  avatar: "Jimmy Kimmel Live!",
  bgFrameColor: "#ffd93f",
  bgFrameOpacity: 1,
  bgFramePosY: 160,
  bgOnlyPosYOffset: 0,
  dividedLineColor: "#202020",
  dividedLinePosY: 12,
  dividedLineStyle: "Wavy",
  line1Color: "#009bdf",
  line1PosY: 2,
  line1Size: 38,
  line1Spacing: -1,
  line1Text: "NOW",
  line2Color: "#ed0080",
  line2PosY: 50,
  line2Size: 24,
  line2Spacing: 0,
  line2Text: "JIMMY KIMMEL LIVE!",
  updateAnim: false
};

let presetBreakingNews = {
  avatar: "CNN",
  bgFrameColor: "#e6e6e6",
  bgFrameOpacity: 1,
  bgFramePosY: 160,
  bgOnlyPosYOffset: 0,
  dividedLineColor: "#202020",
  dividedLinePosY: 12,
  dividedLineStyle: "Dashed",
  line1Color: "#c70913",
  line1PosY: 6,
  line1Size: 30,
  line1Spacing: 0,
  line1Text: "BREAKING NEWS",
  line2Color: "#000000",
  line2PosY: 50,
  line2Size: 22,
  line2Spacing: -0.5,
  line2Text: "20% Wendy's is out of beef",
  updateAnim: false
};

let presetWeather = {
  avatar: "Weather",
  bgFrameColor: "#ffd93f",
  bgFrameOpacity: 1,
  bgFramePosY: 160,
  bgOnlyPosYOffset: 0,
  dividedLineColor: "#202020",
  dividedLinePosY: 10,
  dividedLineStyle: "Wavy",
  line1Color: "#009bdf",
  line1PosY: 2,
  line1Size: 36,
  line1Spacing: 0,
  line1Text: "60° CLOUDY",
  line2Color: "#ed0080",
  line2PosY: 50,
  line2Size: 24,
  line2Spacing: 0,
  line2Text: "BROOKLYN, NY",
  updateAnim: false
};

let presetTheVoice = {
  avatar: "NBC",
  bgFrameColor: "#00dfe4",
  bgFrameOpacity: 1,
  bgFramePosY: 160,
  bgOnlyPosYOffset: 0,
  dividedLineColor: "#202020",
  dividedLinePosY: 14,
  dividedLineStyle: "Dashed",
  line1Color: "#000000",
  line1PosY: 2,
  line1Size: 38,
  line1Spacing: 0,
  line1Text: "#TheVoice",
  line2Color: "#ff3da2",
  line2PosY: 50,
  line2Size: 24,
  line2Spacing: 0,
  line2Text: "SHARE THE MOMENT",
  updateAnim: false
};

let presetTwitter = {
  avatar: "Twitter",
  bgFrameColor: "#ffffff",
  bgFrameOpacity: 1,
  bgFramePosY: 160,
  bgOnlyPosYOffset: 0,
  dividedLineColor: "#202020",
  dividedLinePosY: 12,
  dividedLineStyle: "Dashed",
  line1Color: "#1da1f2",
  line1PosY: 4,
  line1Size: 30,
  line1Spacing: 0,
  line1Text: "@9to5mac",
  line2Color: "#000000",
  line2PosY: 52,
  line2Size: 18,
  line2Spacing: 0,
  line2Text: "Apple announces virtual WWDC",
  updateAnim: false
};

let presetConcentrationTest = {
  avatar: "Play (Magenta)",
  bgFrameColor: "#ffd93f",
  bgFrameOpacity: 1,
  bgFramePosY: 160,
  bgOnlyPosYOffset: 0,
  dividedLineColor: "#202020",
  dividedLinePosY: 10,
  dividedLineStyle: "Wavy",
  line1Color: "#009bdf",
  line1PosY: 6,
  line1Size: 30,
  line1Spacing: 0,
  line1Text: "CONC. SCORE: 32",
  line2Color: "#ed0080",
  line2PosY: 54,
  line2Size: 18,
  line2Spacing: 0,
  line2Text: "YOU MAY NOT LIKE THIS SHOW",
  updateAnim: false
};

let presetYouMayLike = {
  avatar: "Play (Magenta)",
  bgFrameColor: "#ffd93f",
  bgFrameOpacity: 1,
  bgFramePosY: 160,
  bgOnlyPosYOffset: 0,
  dividedLineColor: "#202020",
  dividedLinePosY: 10,
  dividedLineStyle: "Wavy",
  line1Color: "#009bdf",
  line1PosY: 6,
  line1Size: 30,
  line1Spacing: 0,
  line1Text: "YOU MAY LIKE...",
  line2Color: "#ed0080",
  line2PosY: 52,
  line2Size: 20,
  line2Spacing: 0,
  line2Text: "ARRESTED DEVELOPMENT",
  updateAnim: false
};

let presetLiveComments = {
  avatar: "Play (Magenta)",
  bgFrameColor: "#ffd93f",
  bgFrameOpacity: 1,
  bgFramePosY: 160,
  bgOnlyPosYOffset: 0,
  dividedLineColor: "#202020",
  dividedLinePosY: 12,
  dividedLineStyle: "Dashed",
  line1Color: "#009bdf",
  line1PosY: 4,
  line1Size: 30,
  line1Spacing: 0,
  line1Text: "@mikeb2003",
  line2Color: "#ed0080",
  line2PosY: 48,
  line2Size: 24,
  line2Spacing: 0,
  line2Text: '"He is guilty!"',
  updateAnim: false
};

let presetSkipThisScene = {
  avatar: "Play (Magenta)",
  bgFrameColor: "#ffd93f",
  bgFrameOpacity: 1,
  bgFramePosY: 160,
  bgOnlyPosYOffset: 0,
  dividedLineColor: "#202020",
  dividedLinePosY: 12,
  dividedLineStyle: "None",
  line1Color: "#009bdf",
  line1PosY: 8,
  line1Size: 30,
  line1Spacing: 0,
  line1Text: "<u>SKIP THIS SCENE</u>",
  line2Color: "#ed0080",
  line2PosY: 44,
  line2Size: 24,
  line2Spacing: 0,
  line2Text: "NEXT SCENE IN 02:16",
  updateAnim: false
};

let presetMostExcitingPart = {
  avatar: "Play (Magenta)",
  bgFrameColor: "#ffd93f",
  bgFrameOpacity: 1,
  bgFramePosY: 160,
  bgOnlyPosYOffset: 0,
  dividedLineColor: "#202020",
  dividedLinePosY: 10,
  dividedLineStyle: "Wavy",
  line1Color: "#009bdf",
  line1PosY: 6,
  line1Size: 30,
  line1Spacing: -1,
  line1Text: "Most Exciting Part",
  line2Color: "#ed0080",
  line2PosY: 50,
  line2Size: 24,
  line2Spacing: 0,
  line2Text: "in 12:36 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<u>Go Directly</u>",
  updateAnim: false
};
